name: Build Docker image and push to Docker Hub

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: false
        type: string
      CONTEXT:
        required: true
        type: string
      DOCKERHUB_REPOSITORY_NAME:
        required: false
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: false

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-24.04

    steps:
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ inputs.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ input.CONTEXT }}"
          platforms: linux/amd64,linux/arm64
          # push: true
          # tags: ${{ inputs.DOCKERHUB_USERNAME}}/${{ inputs.DOCKERHUB_REPOSITORY_NAME}}:latest