name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api:
    name: Build API image
    uses: ./.github/workflows/step-ci-docker-build-push.yml
    with:
      CONTEXT: api
    secrets: inherit
  
  client:
    name: Build client image
    uses: ./.github/workflows/step-ci-docker-build-push.yml
    with:
      CONTEXT: client
    secrets: inherit