name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  api:
    name: Build and push API image
    uses: ./.github/workflows/step-ci-docker-build-push.yml
    with:
      CONTEXT: api
      DOCKERHUB_USERNAME: butskristof
      DOCKERHUB_REPOSITORY_NAME: resto-2-api
    secrets: inherit
  
  client:
    name: Build and push client image
    uses: ./.github/workflows/step-ci-docker-build-push.yml
    with:
      CONTEXT: client
      DOCKERHUB_USERNAME: butskristof
      DOCKERHUB_REPOSITORY_NAME: resto-2-client
    secrets: inherit