name: 'Build frontend'

on:
  pull_request:
    branches: [main]
    # paths:
    #   - 'client/**'

jobs:
  build:
    name: Format, lint and build SPA
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: './frontend/spa'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
      
      - name: Install
        run: npm ci
      
      - name: Check formatting
        run: npm run format:check
        
      - name: Check linting
        run: npm run lint:check
      
      - name: Build
        run: npm run build